services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyMessenger\:
        resource: '../../{Serializer,Service}'

    Wexample\SymfonyMessenger\Serializer\FailureMessageSerializer:
        arguments:
            $defaultSerializer: '@messenger.default_serializer'

    Wexample\SymfonyMessenger\Service\EntityMessageRegistry:
        arguments:
            $messageClasses: '%wexample_symfony_messenger.message_classes%'
